In [112]:
import numpy as np
import pandas as pd

In [113]:
#sudoku = np.zeros(81,dtype="int").reshape(9,9)
def clear_sudoku():
    sudoku = [[0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0]]

    sudoku = np.array(sudoku)
    return sudoku

In [114]:
def example_sudoku():
    sudoku = [[0, 7, 0, 4, 0, 5, 6, 0, 0],
              [9, 2, 4, 0, 6, 0, 8, 0, 0],
              [1, 0, 5, 0, 0, 8, 7, 0, 0],
              [0, 3, 8, 0, 5, 7, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 7, 3],
              [0, 4, 7, 0, 9, 0, 1, 2, 0],
              [4, 0, 9, 6, 0, 2, 0, 0, 1],
              [7, 0, 0, 8, 3, 0, 4, 0, 9],
              [0, 1, 0, 5, 4, 9, 0, 0, 0]]

    sudoku = np.array(sudoku)
    return sudoku

In [4]:
#sudoku[1,3] - value from row 1 and col 3
#sudoku[:,3] - whole column 3
#sudoku[1,:] - whole row 1

In [115]:
def if_possible(sudoku, row, col, number):
    possible = False
    
    ##check if number in row
    if number not in sudoku[row,:]:
        possible = True
    else:
        return False
    
    ##check if number in column
    if number not in sudoku[:,col]:
        possible = True
    else:
        return False
    
    ##check if number in squere 3x3
    start_sq_row = row // 3 #floor qoutient
    # can make it prettier
    if start_sq_row == 1:
        start_sq_row = 3
    elif start_sq_row ==2:
        start_sq_row = 6
    start_sq_col = col // 3
    if start_sq_col == 1:
        start_sq_col = 3
    elif start_sq_col ==2:
        start_sq_col = 6
        
    end_sq_row = start_sq_row + 3
    end_sq_col = start_sq_col + 3
    
#     print("Starting row of squere: {}".format(start_sq_row))
#     print("Starting column of squere: {}".format(start_sq_col))
#     print("Ending row of squere: {}".format(end_sq_row))
#     print("Ending column of squere: {}".format(end_sq_col))
    
    if number not in sudoku[start_sq_row:end_sq_row,start_sq_col:end_sq_col]:
        possible = True
    else:
        return False
    
    return possible

In [6]:
## checking if function works
#if_possible(sudoku, 1, 6, 1)

In [7]:
## just putting in (biggest - for now) possible number in every place

# i for rows
# for i in range(9):
#     # j for cols
#     for j in range(9):
#         # do only if number is 0 
#         if sudoku[i][j] == 0:
#             # check all numbers
#             for n in range(1,10):
#                 # if possible put number there
#                 if if_possible(sudoku, i, j, n) == True:
#                     sudoku[i][j] = n

In [116]:
## recursive function solving sudoku
# args: sudoku in actual state, row and col that is checked (and filled), number that is checked in this step
def solve(sudoku, on_start, row, col, number):
    #if cell = 0 then start checking possibilities
    if sudoku[row][col] == 0:
        if_possib = if_possible(sudoku, row, col, number)
        #if possible to put number in cell - put number in that cell
        if if_possib == True:
            sudoku[row][col] = number
            #####
            #if last column
            if col == 8:
                #if last row
                if row == 8:
                    #we are in last cell and it is not equal to 0 -> return sudoku
                    return sudoku
                #if not last row
                else:
                    #go to firs (0) column and next row
                    col = 0
                    row = row + 1
            #if not last column
            else:
                #go to next column and stay in same row
                col = col + 1
            #GO TO NEXT CELL #recursive solve with actual state of sudoku, changed row and col and number 1 - because checking values in new cell starts from 1
            return solve(sudoku, on_start, row, col, 1)
            #####
        #if not possible to put number in cell
        else:
            #if number is 9 - error
            if number == 9:
                #INSTEAD OF ERROR NOW I NEED TO PUT HERE MECHANISM THAT WILL GO BACK AND 
                #TRY TO PUT ANOTHER POSSIBLE NUMBER IN PREVIOUS CELL THAT WASN'T FILLED ON START
                #WILL DO IT USING ON_START VARIABLE
                print("error")
                return sudoku
            #if number is not 9 (less than 9) recursive solve with number = number + 1
            else:
                return solve(sudoku, on_start, row, col, number + 1)
    #if cell != 0 then don't check possibilities
    else:
        #####
        #if last column
        if col == 8:
            #if last row
            if row == 8:
                #we are in last cell and it is not equal to 0 -> return sudoku
                return sudoku
            #if not last row
            else:
                #go to firs (0) column and next row
                col = 0
                row = row + 1
        #if not last column
        else:
            #go to next column and stay in same row
            col = col + 1
        #GO TO NEXT CELL #recursive solve with actual state of sudoku, changed row and col and number 1 - because checking values in new cell starts from 1
        return solve(sudoku, on_start, row, col, 1)
        #####
    
    

In [117]:
sudoku = clear_sudoku()
sudoku = example_sudoku()

In [118]:
sudoku

array([[0, 7, 0, 4, 0, 5, 6, 0, 0],
       [9, 2, 4, 0, 6, 0, 8, 0, 0],
       [1, 0, 5, 0, 0, 8, 7, 0, 0],
       [0, 3, 8, 0, 5, 7, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 3],
       [0, 4, 7, 0, 9, 0, 1, 2, 0],
       [4, 0, 9, 6, 0, 2, 0, 0, 1],
       [7, 0, 0, 8, 3, 0, 4, 0, 9],
       [0, 1, 0, 5, 4, 9, 0, 0, 0]])

In [119]:
#on_start is array which have 1 in cells filled no start and 0 it cells not filled
on_start = np.copy(sudoku)
np.place(on_start, on_start>0, [True])
print(on_start)
#print(sudoku)

[[0 1 0 1 0 1 1 0 0]
 [1 1 1 0 1 0 1 0 0]
 [1 0 1 0 0 1 1 0 0]
 [0 1 1 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 1 1]
 [0 1 1 0 1 0 1 1 0]
 [1 0 1 1 0 1 0 0 1]
 [1 0 0 1 1 0 1 0 1]
 [0 1 0 1 1 1 0 0 0]]


In [120]:
sudoku1 = solve(sudoku, on_start, 0, 0, 1)

error


In [121]:
sudoku1

array([[3, 7, 0, 4, 0, 5, 6, 0, 0],
       [9, 2, 4, 0, 6, 0, 8, 0, 0],
       [1, 0, 5, 0, 0, 8, 7, 0, 0],
       [0, 3, 8, 0, 5, 7, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 3],
       [0, 4, 7, 0, 9, 0, 1, 2, 0],
       [4, 0, 9, 6, 0, 2, 0, 0, 1],
       [7, 0, 0, 8, 3, 0, 4, 0, 9],
       [0, 1, 0, 5, 4, 9, 0, 0, 0]])