In this notebook I have made 2nd solving algorithm (see readme)

In [1]:
import numpy as np
import threading
import sys
import datetime

In [2]:
#sudoku = np.zeros(81,dtype="int").reshape(9,9)
def clear_sudoku():
    sudoku = [[0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0]]

    sudoku = np.array(sudoku)
    return sudoku

Examples are from websudoku.com

In [3]:
def example_easy_sudoku():
    sudoku = []
    sudoku.append(np.array([[0, 4, 0, 0, 0, 3, 0, 6, 0],
                 [6, 0, 8, 9, 0, 1, 5, 7, 0],
                 [0, 2, 0, 7, 6, 0, 0, 0, 3],
                 [2, 0, 0, 4, 5, 7, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 2, 1, 9, 0, 0, 6],
                 [3, 0, 0, 0, 9, 4, 0, 5, 0],
                 [0, 9, 5, 6, 0, 2, 8, 0, 1],
                 [0, 7, 0, 1, 0, 0, 0, 9, 0]]))

    sudoku.append(np.array([[0, 5, 0, 1, 4, 0, 0, 0, 2],
                 [7, 0, 1, 0, 0, 9, 0, 0, 4],
                 [4, 3, 0, 6, 0, 0, 0, 0, 0],
                 [5, 0, 3, 0, 9, 1, 2, 0, 0],
                 [0, 1, 0, 3, 0, 6, 0, 5, 0],
                 [0, 0, 7, 5, 2, 0, 6, 0, 1],
                 [0, 0, 0, 0, 0, 8, 0, 9, 5],
                 [9, 0, 0, 4, 0, 0, 8, 0, 3],
                 [1, 0, 0, 0, 7, 3, 0, 2, 0]]))
    
    sudoku.append(np.array([[0, 8, 0, 0, 3, 5, 9, 0, 0],
                 [0, 0, 6, 1, 0, 0, 0, 0, 0],
                 [2, 0, 0, 0, 9, 0, 8, 7, 0],
                 [0, 0, 0, 3, 5, 0, 1, 2, 4],
                 [1, 4, 3, 0, 0, 0, 7, 5, 8],
                 [5, 7, 2, 0, 4, 1, 0, 0, 0],
                 [0, 2, 9, 0, 7, 0, 0, 0, 6],
                 [0, 0, 0, 0, 0, 4, 2, 0, 0],
                 [0, 0, 4, 9, 2, 0, 0, 3, 0]]))

    return sudoku

In [4]:
def example_medium_sudoku():
    sudoku = []
    sudoku.append(np.array([[0, 8, 6, 3, 0, 0, 0, 0, 4],
                 [0, 0, 1, 0, 9, 0, 0, 0, 0],
                 [0, 0, 0, 4, 1, 2, 0, 6, 0],
                 [5, 1, 0, 0, 0, 0, 0, 0, 3],
                 [6, 0, 3, 0, 5, 0, 8, 0, 1],
                 [8, 0, 0, 0, 0, 0, 0, 7, 5],
                 [0, 4, 0, 5, 6, 7, 0, 0, 0],
                 [0, 0, 0, 0, 8, 0, 2, 0, 0],
                 [7, 0, 0, 0, 0, 3, 1, 5, 0]]))

    sudoku.append(np.array([[9, 7, 0, 4, 0, 0, 0, 0, 5],
                 [0, 8, 3, 2, 0, 5, 0, 0, 0],
                 [0, 0, 4, 6, 0, 0, 7, 0, 0],
                 [7, 3, 0, 8, 0, 0, 0, 4, 0],
                 [0, 0, 0, 7, 0, 1, 0, 0, 0],
                 [0, 1, 0, 0, 0, 3, 0, 6, 7],
                 [0, 0, 1, 0, 0, 4, 8, 0, 0],
                 [0, 0, 0, 3, 0, 6, 4, 5, 0],
                 [6, 0, 0, 0, 0, 7, 0, 3, 2]]))
    
    sudoku.append(np.array([[0, 4, 0, 0, 0, 0, 0, 9, 3],
                 [0, 0, 0, 0, 5, 0, 7, 0, 0],
                 [0, 0, 0, 0, 3, 2, 5, 0, 6],
                 [0, 0, 0, 0, 0, 0, 9, 0, 7],
                 [5, 2, 0, 7, 9, 6, 0, 8, 4],
                 [7, 0, 1, 0, 0, 0, 0, 0, 0],
                 [3, 0, 8, 9, 2, 0, 0, 0, 0],
                 [0, 0, 2, 0, 6, 0, 0, 0, 0],
                 [9, 6, 0, 0, 0, 0, 0, 3, 0]]))

    return sudoku

In [5]:
def example_hard_sudoku():
    sudoku = []
    sudoku.append(np.array([[0, 0, 0, 0, 0, 5, 0, 0, 0],
                 [0, 0, 7, 6, 0, 0, 4, 0, 0],
                 [3, 0, 0, 0, 7, 0, 0, 1, 0],
                 [0, 0, 9, 0, 0, 8, 0, 5, 0],
                 [5, 0, 3, 9, 0, 2, 6, 0, 1],
                 [0, 4, 0, 1, 0, 0, 2, 0, 0],
                 [0, 3, 0, 0, 8, 0, 0, 0, 9],
                 [0, 0, 6, 0, 0, 4, 5, 0, 0],
                 [0, 0, 0, 7, 0, 0, 0, 0, 0]]))

    sudoku.append(np.array([[0, 3, 7, 0, 5, 0, 0, 0, 0],
                 [0, 0, 0, 6, 8, 0, 0, 0, 2],
                 [0, 0, 4, 0, 2, 0, 0, 1, 0],
                 [0, 0, 0, 0, 0, 5, 0, 0, 6],
                 [9, 2, 0, 0, 0, 0, 0, 4, 1],
                 [1, 0, 0, 2, 0, 0, 0, 0, 0],
                 [0, 6, 0, 0, 4, 0, 2, 0, 0],
                 [4, 0, 0, 0, 3, 2, 0, 0, 0],
                 [0, 0, 0, 0, 6, 0, 3, 7, 0]]))
    
    sudoku.append(np.array([[6, 0, 0, 5, 0, 0, 0, 0, 1],
                 [0, 9, 0, 7, 0, 8, 5, 0, 0],
                 [0, 1, 0, 3, 0, 0, 0, 8, 0],
                 [1, 0, 8, 0, 3, 0, 6, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 6, 0, 8, 0, 3, 0, 9],
                 [0, 4, 0, 0, 0, 3, 0, 9, 0],
                 [0, 0, 9, 2, 0, 5, 0, 1, 0],
                 [8, 0, 0, 0, 0, 9, 0, 0, 7]]))

    return sudoku

In [6]:
def example_evil_sudoku():
    sudoku = []
    sudoku.append(np.array([[6, 0, 0, 4, 0, 0, 0, 0, 0],
                 [0, 0, 2, 0, 5, 3, 0, 1, 0],
                 [8, 0, 0, 0, 2, 0, 0, 0, 4],
                 [1, 0, 9, 5, 0, 0, 7, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 6, 0, 0, 4, 9, 0, 5],
                 [2, 0, 0, 0, 6, 0, 0, 0, 7],
                 [0, 3, 0, 9, 4, 0, 2, 0, 0],
                 [0, 0, 0, 0, 0, 8, 0, 0, 9]]))

    sudoku.append(np.array([[0, 3, 7, 0, 5, 0, 0, 0, 0],
                 [0, 0, 0, 6, 8, 0, 0, 0, 2],
                 [0, 0, 4, 0, 2, 0, 0, 1, 0],
                 [0, 0, 0, 0, 0, 5, 0, 0, 6],
                 [9, 2, 0, 0, 0, 0, 0, 4, 1],
                 [1, 0, 0, 2, 0, 0, 0, 0, 0],
                 [0, 6, 0, 0, 4, 0, 2, 0, 0],
                 [4, 0, 0, 0, 3, 2, 0, 0, 0],
                 [0, 0, 0, 0, 6, 0, 3, 7, 0]]))
    
    sudoku.append(np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 5, 3, 0, 0, 4, 8, 7, 0],
                 [0, 0, 0, 0, 0, 1, 4, 0, 9],
                 [0, 1, 0, 0, 6, 0, 0, 0, 0],
                 [7, 9, 0, 0, 0, 0, 0, 3, 4],
                 [0, 0, 0, 0, 1, 0, 0, 2, 0],
                 [3, 0, 5, 6, 0, 0, 0, 0, 0],
                 [0, 8, 1, 3, 0, 0, 2, 9, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0]]))

    return sudoku

In [7]:
#sudoku[1,3] - value from row 1 and col 3
#sudoku[:,3] - whole column 3
#sudoku[1,:] - whole row 1

In [8]:
def if_possible(sudoku, row, col, number):
    possible = False
    
    ##check if number in row
    if number not in sudoku[row,:]:
        possible = True
    else:
        return False
    
    ##check if number in column
    if number not in sudoku[:,col]:
        possible = True
    else:
        return False
    
    ##check if number in squere 3x3
    start_sq_row = row // 3 #floor qoutient
    # can make it prettier
    if start_sq_row == 1:
        start_sq_row = 3
    elif start_sq_row ==2:
        start_sq_row = 6
    start_sq_col = col // 3
    if start_sq_col == 1:
        start_sq_col = 3
    elif start_sq_col ==2:
        start_sq_col = 6
        
    end_sq_row = start_sq_row + 3
    end_sq_col = start_sq_col + 3
    
#     print("Starting row of squere: {}".format(start_sq_row))
#     print("Starting column of squere: {}".format(start_sq_col))
#     print("Ending row of squere: {}".format(end_sq_row))
#     print("Ending column of squere: {}".format(end_sq_col))
    
    if number not in sudoku[start_sq_row:end_sq_row,start_sq_col:end_sq_col]:
        possible = True
    else:
        return False
    
    return possible

In [9]:
## checking if function works
#if_possible(sudoku, 1, 6, 1)

In [10]:
def restart_higher_order_put(sudoku, safe_cells, order, order_put):
    for i in range(9):
        for j in range(9):
            if order[i][j] > order_put:
                order[i][j] = 0
                sudoku[i][j] = 0
                safe_cells[i][j] = 0
    return sudoku, safe_cells, order

In [11]:
###
# pierwsze wywolanie: 
# sudoku = sudoku
# safe_cells = on_start
# rec = 1
#
# sprawdzanie kazdej komórki 
#
# sudoku jest aktualizowane co krok o te pozycje które są pewne
# safe_cells są rozszerzane o te pozycje które są pewne
# rec powiększane o 1

In [12]:
# #first try - without go back
# def solve(sudoku, safe_cells, rec):
#     if rec % 10 == 0:
#         print("Recursion: {}".format(rec))
        
#     for i in range(9):
#         for j in range(9):
#             if safe_cells[i][j] == 0:
#                 count = 0
#                 num = None
            
#                 for n in range(1,10):
#                     if if_possible(sudoku, i, j, n) == True:
#                         count = count + 1
#                         # if there will be only one possible it will be placed in next if statement
#                         num = n  

#                 if count == 1:
#                     sudoku[i][j] = num
#                     safe_cells[i][j] = 1
#     if safe_cells.sum() == 81:
#         return sudoku
#     else:
#         return solve(sudoku, safe_cells, rec+1)

In [13]:
#second try - with go back
def solve(sudoku, safe_cells, order, order_put, go_back, rec):
    
    if rec == 1:
        print(datetime.datetime.now())
        
    #printing recursion step
    if rec % 100 == 0:  
        print("Recursion: {}".format(rec))
        
    #if going back 
    if go_back == True:
        row_col = np.where(order == order_put)
        # if there is more than 1 order_put in order that means these cell had only 1 possibility so just go back a stap more
        
        if row_col[0].shape[0] > 1:
            go_back = True
            order_put = order_put - 1

            sudoku, safe_cells, order = restart_higher_order_put(sudoku, safe_cells, order, order_put)

            return solve(sudoku, safe_cells, order, order_put, go_back, rec + 1)
        
        #print(row_col)
        row = row_col[0][0]
        col = row_col[1][0]
        
        num = sudoku[row][col]
        if num == 9:
            #print("No other number can be put in place: [{}][{}]".format( row, col))
            # if it went back to the start there is an error
            if order_put == 1:
                #print("ERROR, can't go back. Actual order_put is {}".format(order_put))
                print("Recursion: {}".format(rec))
                print(datetime.datetime.now())
                return sudoku
            # if can't put in this cell go to previous order_put
            else:
                go_back = True
                order_put = order_put - 1

                sudoku, safe_cells, order = restart_higher_order_put(sudoku, safe_cells, order, order_put)

                return solve(sudoku, safe_cells, order, order_put, go_back, rec + 1)
        for n in range(num+1, 10):
            # if possible to put number in cell
            if if_possible(sudoku, row, col, n) == True:
                #print("It'is possible to put: {} in place: [{}][{}]".format(n, row, col))
                sudoku[row][col] = n
                safe_cells[row][col] = 1
                order[row][col] = order_put
                order_put = order_put + 1
                go_back = False
                
                # ending if
                if safe_cells.sum() == 81:
                    print("Recursion: {}".format(rec))
                    print(datetime.datetime.now())
                    return sudoku
                else:
                    return solve(sudoku, safe_cells, order, order_put, go_back, rec+1)
                
            # if can't put different number in this cell
            else:
                if n == 9:
                    #print("No other number can be put in place: [{}][{}]".format( row, col))
                    # if it went back to the start there is an error
                    if order_put == 1:
                        #print("ERROR, can't go back. Actual order_put is {}".format(order_put))
                        print("Recursion: {}".format(rec))
                        print(datetime.datetime.now())
                        return sudoku
                    # if can't put in this cell go to previous order_put
                    else:
                        go_back = True
                        order_put = order_put - 1

                        sudoku, safe_cells, order = restart_higher_order_put(sudoku, safe_cells, order, order_put)

                        return solve(sudoku, safe_cells, order, order_put, go_back, rec + 1)
                
    #if not going back
    else:
        count_table = np.zeros(81,dtype="int").reshape(9,9)

        for i in range(9):
            for j in range(9):
                if safe_cells[i][j] == 0:
                    count = 0
                    num = None

                    for n in range(1,10):
                        if if_possible(sudoku, i, j, n) == True:
                            count = count + 1
                            num = n

                    count_table[i][j] = count

                    # if there will be 1 possiblity it will be put in cell
                    if count == 1:
                        sudoku[i][j] = num
                        safe_cells[i][j] = 1
                        order[i][j] = order_put
                        # not incrementing order_put so all sure cells will be in the same step in history
                        go_back = False
        
        #error, there is no possibility to put in a number in any cell
        if count_table.sum() == 0:
            go_back = True
            order_put = order_put - 1

            sudoku, safe_cells, order = restart_higher_order_put(sudoku, safe_cells, order, order_put)

            return solve(sudoku, safe_cells, order, order_put, go_back, rec + 1)

        #if there won't be only 1 possibility in any cell do algorithm to put one of possibilities and go on and then go back at some point
        if 1 not in count_table and safe_cells.sum() != 81:    
            min_pos = count_table[count_table > 1].min()

            for i in range(9):
                for j in range(9):
                    if count_table[i][j] == min_pos:
                        for n in range(1,10):
                            if if_possible(sudoku, i, j, n) == True:
                                sudoku[i][j] = n
                                safe_cells[i][j] = 1
                                order[i][j] = order_put
                                order_put = order_put + 1
                                go_back = False
                                return solve(sudoku, safe_cells, order, order_put, go_back, rec + 1)
                                
            #print(sudoku)
            #print(safe_cells.sum())
            #print(min_pos)
    order_put = order_put + 1
            
    # ending if
    if safe_cells.sum() == 81:
        print("Recursion: {}".format(rec))
        print(datetime.datetime.now())
        return sudoku
    else:
        return solve(sudoku, safe_cells, order, order_put, go_back, rec+1)

In [14]:
arr = np.array([[0,1,2,3],[6,3,3,3]])

In [15]:
res = np.where(arr==10)
print(res[0].shape[0])

print(res[0])
print(res[1])

0
[]
[]


In [16]:
#sudoku = clear_sudoku()
#sudoku = example_easy_sudoku()
#sudoku = example_medium_sudoku()
#sudoku = example_hard_sudoku()
sudoku = example_evil_sudoku()

In [17]:
sudoku

[array([[6, 0, 0, 4, 0, 0, 0, 0, 0],
        [0, 0, 2, 0, 5, 3, 0, 1, 0],
        [8, 0, 0, 0, 2, 0, 0, 0, 4],
        [1, 0, 9, 5, 0, 0, 7, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 6, 0, 0, 4, 9, 0, 5],
        [2, 0, 0, 0, 6, 0, 0, 0, 7],
        [0, 3, 0, 9, 4, 0, 2, 0, 0],
        [0, 0, 0, 0, 0, 8, 0, 0, 9]]), array([[0, 3, 7, 0, 5, 0, 0, 0, 0],
        [0, 0, 0, 6, 8, 0, 0, 0, 2],
        [0, 0, 4, 0, 2, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 5, 0, 0, 6],
        [9, 2, 0, 0, 0, 0, 0, 4, 1],
        [1, 0, 0, 2, 0, 0, 0, 0, 0],
        [0, 6, 0, 0, 4, 0, 2, 0, 0],
        [4, 0, 0, 0, 3, 2, 0, 0, 0],
        [0, 0, 0, 0, 6, 0, 3, 7, 0]]), array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 5, 3, 0, 0, 4, 8, 7, 0],
        [0, 0, 0, 0, 0, 1, 4, 0, 9],
        [0, 1, 0, 0, 6, 0, 0, 0, 0],
        [7, 9, 0, 0, 0, 0, 0, 3, 4],
        [0, 0, 0, 0, 1, 0, 0, 2, 0],
        [3, 0, 5, 6, 0, 0, 0, 0, 0],
        [0, 8, 1, 3, 0, 0, 2, 9, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [18]:
safe_cells = np.copy(sudoku)
np.place(safe_cells, safe_cells>0, [True])
print(safe_cells)
#print(sudoku)

[[[1 0 0 1 0 0 0 0 0]
  [0 0 1 0 1 1 0 1 0]
  [1 0 0 0 1 0 0 0 1]
  [1 0 1 1 0 0 1 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 1 0 0 1 1 0 1]
  [1 0 0 0 1 0 0 0 1]
  [0 1 0 1 1 0 1 0 0]
  [0 0 0 0 0 1 0 0 1]]

 [[0 1 1 0 1 0 0 0 0]
  [0 0 0 1 1 0 0 0 1]
  [0 0 1 0 1 0 0 1 0]
  [0 0 0 0 0 1 0 0 1]
  [1 1 0 0 0 0 0 1 1]
  [1 0 0 1 0 0 0 0 0]
  [0 1 0 0 1 0 1 0 0]
  [1 0 0 0 1 1 0 0 0]
  [0 0 0 0 1 0 1 1 0]]

 [[0 0 0 0 0 0 0 0 0]
  [0 1 1 0 0 1 1 1 0]
  [0 0 0 0 0 1 1 0 1]
  [0 1 0 0 1 0 0 0 0]
  [1 1 0 0 0 0 0 1 1]
  [0 0 0 0 1 0 0 1 0]
  [1 0 1 1 0 0 0 0 0]
  [0 1 1 1 0 0 1 1 0]
  [0 0 0 0 0 0 0 0 0]]]


In [19]:
safe_cells[0].sum()

26

In [20]:
order = [np.zeros(81,dtype="int").reshape(9,9), np.zeros(81,dtype="int").reshape(9,9), np.zeros(81,dtype="int").reshape(9,9)]
order_put = [1,1,1]
rec = [1,1,1]

In [21]:
# for easier sudoku
#%%time
#sudoku = solve(sudoku, on_start, 0, 0, 1, go_back=False, rec=0)

In [22]:
#sudoku

In [23]:
threading.stack_size(67108864) # 64MB stack
sys.setrecursionlimit(2 ** 20) # something real big
                               # you actually hit the 64MB limit first
                               # going by other answers, could just use 2**32-1

In [24]:
thread = threading.Thread(target=solve, args = (sudoku[0], safe_cells[0], order[0], order_put[0], False, rec[0], ))
thread.start()

2020-02-27 13:33:38.998167
Recursion: 100
Recursion: 200
Recursion: 300
Recursion: 400
Recursion: 500
Recursion: 600
Recursion: 700
Recursion: 800
Recursion: 900
Recursion: 1000
Recursion: 1100
Recursion: 1200
Recursion: 1300
Recursion: 1400
Recursion: 1500
Recursion: 1600
Recursion: 1700
Recursion: 1800
Recursion: 1900
Recursion: 2000
Recursion: 2100
Recursion: 2200
Recursion: 2300
Recursion: 2400
Recursion: 2500
Recursion: 2600
Recursion: 2700
Recursion: 2800
Recursion: 2900
Recursion: 3000
Recursion: 3049
2020-02-27 13:33:40.185644


In [25]:
thread = threading.Thread(target=solve, args = (sudoku[1], safe_cells[1], order[1], order_put[1], False, rec[1], ))
thread.start()

2020-02-27 13:33:42.422004
Recursion: 100
Recursion: 200
Recursion: 300
Recursion: 400
Recursion: 500
Recursion: 600
Recursion: 700
Recursion: 800
Recursion: 900
Recursion: 1000
Recursion: 1100
Recursion: 1200
Recursion: 1300
Recursion: 1400
Recursion: 1500
Recursion: 1600
Recursion: 1700
Recursion: 1800
Recursion: 1900
Recursion: 2000
Recursion: 2100
Recursion: 2200
Recursion: 2300
Recursion: 2400
Recursion: 2500
Recursion: 2600
Recursion: 2700
Recursion: 2800
Recursion: 2801
2020-02-27 13:33:43.186314


In [26]:
thread = threading.Thread(target=solve, args = (sudoku[2], safe_cells[2], order[2], order_put[2], False, rec[2], ))
thread.start()

2020-02-27 13:33:45.561401
Recursion: 100
Recursion: 200
Recursion: 300
Recursion: 400
Recursion: 500
Recursion: 600
Recursion: 700
Recursion: 800
Recursion: 900
Recursion: 942
2020-02-27 13:33:45.899948


In [27]:
sudoku

[array([[6, 1, 3, 4, 8, 9, 5, 7, 2],
        [9, 4, 2, 7, 5, 3, 6, 1, 8],
        [8, 5, 7, 1, 2, 6, 3, 9, 4],
        [1, 8, 9, 5, 3, 2, 7, 4, 6],
        [4, 2, 5, 6, 9, 7, 1, 8, 3],
        [3, 7, 6, 8, 1, 4, 9, 2, 5],
        [2, 9, 4, 3, 6, 1, 8, 5, 7],
        [7, 3, 8, 9, 4, 5, 2, 6, 1],
        [5, 6, 1, 2, 7, 8, 4, 3, 9]]), array([[2, 3, 7, 1, 5, 4, 6, 8, 9],
        [5, 9, 1, 6, 8, 7, 4, 3, 2],
        [6, 8, 4, 9, 2, 3, 5, 1, 7],
        [3, 7, 8, 4, 1, 5, 9, 2, 6],
        [9, 2, 5, 3, 7, 6, 8, 4, 1],
        [1, 4, 6, 2, 9, 8, 7, 5, 3],
        [7, 6, 3, 8, 4, 1, 2, 9, 5],
        [4, 5, 9, 7, 3, 2, 1, 6, 8],
        [8, 1, 2, 5, 6, 9, 3, 7, 4]]), array([[1, 4, 9, 7, 8, 6, 3, 5, 2],
        [6, 5, 3, 2, 9, 4, 8, 7, 1],
        [2, 7, 8, 5, 3, 1, 4, 6, 9],
        [5, 1, 2, 4, 6, 3, 9, 8, 7],
        [7, 9, 6, 8, 5, 2, 1, 3, 4],
        [8, 3, 4, 9, 1, 7, 6, 2, 5],
        [3, 2, 5, 6, 4, 9, 7, 1, 8],
        [4, 8, 1, 3, 7, 5, 2, 9, 6],
        [9, 6, 7, 1, 2, 8, 5, 4, 3]]