In this notebook I have made 1st solving algorithm (see readme)

In [1]:
import numpy as np
import threading
import sys
import datetime

In [2]:
#sudoku = np.zeros(81,dtype="int").reshape(9,9)
def clear_sudoku():
    sudoku = [[0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0]]

    sudoku = np.array(sudoku)
    return sudoku

Examples are from websudoku.com

In [3]:
def example_easy_sudoku():
    sudoku = []
    sudoku.append(np.array([[0, 4, 0, 0, 0, 3, 0, 6, 0],
                 [6, 0, 8, 9, 0, 1, 5, 7, 0],
                 [0, 2, 0, 7, 6, 0, 0, 0, 3],
                 [2, 0, 0, 4, 5, 7, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 2, 1, 9, 0, 0, 6],
                 [3, 0, 0, 0, 9, 4, 0, 5, 0],
                 [0, 9, 5, 6, 0, 2, 8, 0, 1],
                 [0, 7, 0, 1, 0, 0, 0, 9, 0]]))

    sudoku.append(np.array([[0, 5, 0, 1, 4, 0, 0, 0, 2],
                 [7, 0, 1, 0, 0, 9, 0, 0, 4],
                 [4, 3, 0, 6, 0, 0, 0, 0, 0],
                 [5, 0, 3, 0, 9, 1, 2, 0, 0],
                 [0, 1, 0, 3, 0, 6, 0, 5, 0],
                 [0, 0, 7, 5, 2, 0, 6, 0, 1],
                 [0, 0, 0, 0, 0, 8, 0, 9, 5],
                 [9, 0, 0, 4, 0, 0, 8, 0, 3],
                 [1, 0, 0, 0, 7, 3, 0, 2, 0]]))
    
    sudoku.append(np.array([[0, 8, 0, 0, 3, 5, 9, 0, 0],
                 [0, 0, 6, 1, 0, 0, 0, 0, 0],
                 [2, 0, 0, 0, 9, 0, 8, 7, 0],
                 [0, 0, 0, 3, 5, 0, 1, 2, 4],
                 [1, 4, 3, 0, 0, 0, 7, 5, 8],
                 [5, 7, 2, 0, 4, 1, 0, 0, 0],
                 [0, 2, 9, 0, 7, 0, 0, 0, 6],
                 [0, 0, 0, 0, 0, 4, 2, 0, 0],
                 [0, 0, 4, 9, 2, 0, 0, 3, 0]]))

    return sudoku

In [4]:
def example_medium_sudoku():
    sudoku = []
    sudoku.append(np.array([[0, 8, 6, 3, 0, 0, 0, 0, 4],
                 [0, 0, 1, 0, 9, 0, 0, 0, 0],
                 [0, 0, 0, 4, 1, 2, 0, 6, 0],
                 [5, 1, 0, 0, 0, 0, 0, 0, 3],
                 [6, 0, 3, 0, 5, 0, 8, 0, 1],
                 [8, 0, 0, 0, 0, 0, 0, 7, 5],
                 [0, 4, 0, 5, 6, 7, 0, 0, 0],
                 [0, 0, 0, 0, 8, 0, 2, 0, 0],
                 [7, 0, 0, 0, 0, 3, 1, 5, 0]]))

    sudoku.append(np.array([[9, 7, 0, 4, 0, 0, 0, 0, 5],
                 [0, 8, 3, 2, 0, 5, 0, 0, 0],
                 [0, 0, 4, 6, 0, 0, 7, 0, 0],
                 [7, 3, 0, 8, 0, 0, 0, 4, 0],
                 [0, 0, 0, 7, 0, 1, 0, 0, 0],
                 [0, 1, 0, 0, 0, 3, 0, 6, 7],
                 [0, 0, 1, 0, 0, 4, 8, 0, 0],
                 [0, 0, 0, 3, 0, 6, 4, 5, 0],
                 [6, 0, 0, 0, 0, 7, 0, 3, 2]]))
    
    sudoku.append(np.array([[0, 4, 0, 0, 0, 0, 0, 9, 3],
                 [0, 0, 0, 0, 5, 0, 7, 0, 0],
                 [0, 0, 0, 0, 3, 2, 5, 0, 6],
                 [0, 0, 0, 0, 0, 0, 9, 0, 7],
                 [5, 2, 0, 7, 9, 6, 0, 8, 4],
                 [7, 0, 1, 0, 0, 0, 0, 0, 0],
                 [3, 0, 8, 9, 2, 0, 0, 0, 0],
                 [0, 0, 2, 0, 6, 0, 0, 0, 0],
                 [9, 6, 0, 0, 0, 0, 0, 3, 0]]))

    return sudoku

In [5]:
def example_hard_sudoku():
    sudoku = []
    sudoku.append(np.array([[0, 0, 0, 0, 0, 5, 0, 0, 0],
                 [0, 0, 7, 6, 0, 0, 4, 0, 0],
                 [3, 0, 0, 0, 7, 0, 0, 1, 0],
                 [0, 0, 9, 0, 0, 8, 0, 5, 0],
                 [5, 0, 3, 9, 0, 2, 6, 0, 1],
                 [0, 4, 0, 1, 0, 0, 2, 0, 0],
                 [0, 3, 0, 0, 8, 0, 0, 0, 9],
                 [0, 0, 6, 0, 0, 4, 5, 0, 0],
                 [0, 0, 0, 7, 0, 0, 0, 0, 0]]))

    sudoku.append(np.array([[0, 3, 7, 0, 5, 0, 0, 0, 0],
                 [0, 0, 0, 6, 8, 0, 0, 0, 2],
                 [0, 0, 4, 0, 2, 0, 0, 1, 0],
                 [0, 0, 0, 0, 0, 5, 0, 0, 6],
                 [9, 2, 0, 0, 0, 0, 0, 4, 1],
                 [1, 0, 0, 2, 0, 0, 0, 0, 0],
                 [0, 6, 0, 0, 4, 0, 2, 0, 0],
                 [4, 0, 0, 0, 3, 2, 0, 0, 0],
                 [0, 0, 0, 0, 6, 0, 3, 7, 0]]))
    
    sudoku.append(np.array([[6, 0, 0, 5, 0, 0, 0, 0, 1],
                 [0, 9, 0, 7, 0, 8, 5, 0, 0],
                 [0, 1, 0, 3, 0, 0, 0, 8, 0],
                 [1, 0, 8, 0, 3, 0, 6, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 6, 0, 8, 0, 3, 0, 9],
                 [0, 4, 0, 0, 0, 3, 0, 9, 0],
                 [0, 0, 9, 2, 0, 5, 0, 1, 0],
                 [8, 0, 0, 0, 0, 9, 0, 0, 7]]))

    return sudoku

In [6]:
def example_evil_sudoku():
    sudoku = []
    sudoku.append(np.array([[6, 0, 0, 4, 0, 0, 0, 0, 0],
                 [0, 0, 2, 0, 5, 3, 0, 1, 0],
                 [8, 0, 0, 0, 2, 0, 0, 0, 4],
                 [1, 0, 9, 5, 0, 0, 7, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 6, 0, 0, 4, 9, 0, 5],
                 [2, 0, 0, 0, 6, 0, 0, 0, 7],
                 [0, 3, 0, 9, 4, 0, 2, 0, 0],
                 [0, 0, 0, 0, 0, 8, 0, 0, 9]]))

    sudoku.append(np.array([[0, 3, 7, 0, 5, 0, 0, 0, 0],
                 [0, 0, 0, 6, 8, 0, 0, 0, 2],
                 [0, 0, 4, 0, 2, 0, 0, 1, 0],
                 [0, 0, 0, 0, 0, 5, 0, 0, 6],
                 [9, 2, 0, 0, 0, 0, 0, 4, 1],
                 [1, 0, 0, 2, 0, 0, 0, 0, 0],
                 [0, 6, 0, 0, 4, 0, 2, 0, 0],
                 [4, 0, 0, 0, 3, 2, 0, 0, 0],
                 [0, 0, 0, 0, 6, 0, 3, 7, 0]]))
    
    sudoku.append(np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 5, 3, 0, 0, 4, 8, 7, 0],
                 [0, 0, 0, 0, 0, 1, 4, 0, 9],
                 [0, 1, 0, 0, 6, 0, 0, 0, 0],
                 [7, 9, 0, 0, 0, 0, 0, 3, 4],
                 [0, 0, 0, 0, 1, 0, 0, 2, 0],
                 [3, 0, 5, 6, 0, 0, 0, 0, 0],
                 [0, 8, 1, 3, 0, 0, 2, 9, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0]]))

    return sudoku

In [7]:
#sudoku[1,3] - value from row 1 and col 3
#sudoku[:,3] - whole column 3
#sudoku[1,:] - whole row 1

In [8]:
def if_possible(sudoku, row, col, number):
    possible = False
    
    ##check if number in row
    if number not in sudoku[row,:]:
        possible = True
    else:
        return False
    
    ##check if number in column
    if number not in sudoku[:,col]:
        possible = True
    else:
        return False
    
    ##check if number in squere 3x3
    start_sq_row = row // 3 #floor qoutient
    # can make it prettier
    if start_sq_row == 1:
        start_sq_row = 3
    elif start_sq_row ==2:
        start_sq_row = 6
    start_sq_col = col // 3
    if start_sq_col == 1:
        start_sq_col = 3
    elif start_sq_col ==2:
        start_sq_col = 6
        
    end_sq_row = start_sq_row + 3
    end_sq_col = start_sq_col + 3
    
#     print("Starting row of squere: {}".format(start_sq_row))
#     print("Starting column of squere: {}".format(start_sq_col))
#     print("Ending row of squere: {}".format(end_sq_row))
#     print("Ending column of squere: {}".format(end_sq_col))
    
    if number not in sudoku[start_sq_row:end_sq_row,start_sq_col:end_sq_col]:
        possible = True
    else:
        return False
    
    return possible

In [9]:
## checking if function works
#if_possible(sudoku, 1, 6, 1)

In [10]:
## just putting in (biggest - for now) possible number in every place

# i for rows
# for i in range(9):
#     # j for cols
#     for j in range(9):
#         # do only if number is 0 
#         if sudoku[i][j] == 0:
#             # check all numbers
#             for n in range(1,10):
#                 # if possible put number there
#                 if if_possible(sudoku, i, j, n) == True:
#                     sudoku[i][j] = n

In [11]:
def restart_next_cells(sudoku, on_start, row, col):
    for i in range(row,9):
        for j in range(9):
            if on_start[i][j] == 0:
                if i == row:
                    if j >= col:
                        sudoku[i][j] = 0
                else:
                    sudoku[i][j] = 0
    return sudoku

In [12]:
## recursive function solving sudoku
# args: sudoku in actual state, row and col that is checked (and filled), number that is checked in this step
def solve(sudoku, on_start, row, col, number, go_back,rec):
    if rec == 1:
        print(datetime.datetime.now())
    
    if rec % 1000 == 0:
        print("Recursion: {}".format(rec))
        
    #if going back and number wasn't filled on start
    if go_back == True and on_start[row][col] == 0:
        #increment number 
        number = sudoku[row][col] + 1
        #if number > 9 error
        if number > 9:
            #INSTEAD OF ERROR NOW I NEED TO PUT HERE MECHANISM THAT WILL GO BACK AND 
            #TRY TO PUT ANOTHER POSSIBLE NUMBER IN PREVIOUS CELL THAT WASN'T FILLED ON START
            #WILL DO IT USING ON_START VARIABLE
            sudoku = restart_next_cells(sudoku, on_start, row, col)
            if col == 0:
                if row == 0:
                    print("Recursion: {}".format(rec))
                    print(datetime.datetime.now())
                    return sudoku
                else:
                    col = 8
                    row = row - 1
            else:
                col = col - 1
            
            return solve(sudoku, on_start, row, col, 0, go_back=True,rec = rec + 1)
        #if number <= 9 check if possible and put number in cell 
        else:
            #if possible to put there number incremented 
            if_possib = if_possible(sudoku, row, col, number)
            if if_possib == True:
                #put number in cell
                sudoku[row][col] = number
                #####
                #if last column
                if col == 8:
                    #if last row
                    if row == 8:
                        #we are in last cell and it is not equal to 0 -> return sudoku
                        print("Recursion: {}".format(rec))
                        print(datetime.datetime.now())
                        return sudoku
                    #if not last row
                    else:
                        #go to firs (0) column and next row
                        col = 0
                        row = row + 1
                #if not last column
                else:
                    #go to next column and stay in same row
                    col = col + 1
                #GO TO NEXT CELL #recursive solve with actual state of sudoku, changed row and col and number 1 - because checking values in new cell starts from 1
                return solve(sudoku, on_start, row, col, 1, go_back=False,rec = rec + 1)
                #####
            else:
                #if number is 9 - error
                if number > 9:
                    #INSTEAD OF ERROR NOW I NEED TO PUT HERE MECHANISM THAT WILL GO BACK AND 
                    #TRY TO PUT ANOTHER POSSIBLE NUMBER IN PREVIOUS CELL THAT WASN'T FILLED ON START
                    #WILL DO IT USING ON_START VARIABLE
                    sudoku = restart_next_cells(sudoku, on_start, row, col)
                    if col == 0:
                        if row == 0:
                            print("Recursion: {}".format(rec))
                            print(datetime.datetime.now())
                            return sudoku
                        else:
                            col = 8
                            row = row - 1
                    else:
                        col = col - 1
                    return solve(sudoku, on_start, row, col, 0, go_back=True,rec = rec + 1)
                #if number is not 9 (less than 9) recursive solve with number = number + 1
                else:
                    return solve(sudoku, on_start, row, col, number, go_back=False,rec = rec + 1)
    #when going back cell filled on start just go back
    elif go_back == True and on_start[row][col]==1:
        if col == 0:
            if row == 0:
                print("Recursion: {}".format(rec))
                print(datetime.datetime.now())
                return sudoku
            else:
                col = 8
                row = row - 1
        else:
            col = col - 1
        return solve(sudoku, on_start, row, col, 0, go_back=True,rec = rec + 1)
    #if not going back
    elif go_back == False:
        #if cell = 0 then start checking possibilities
        if on_start[row][col] == 0:
            if_possib = if_possible(sudoku, row, col, number)
            #if possible to put number in cell - put number in that cell
            if if_possib == True:
                sudoku[row][col] = number
                #####
                #if last column
                if col == 8:
                    #if last row
                    if row == 8:
                        #we are in last cell and it is not equal to 0 -> return sudoku
                        print("Recursion: {}".format(rec))
                        print(datetime.datetime.now())
                        return sudoku
                    #if not last row
                    else:
                        #go to firs (0) column and next row
                        col = 0
                        row = row + 1
                #if not last column
                else:
                    #go to next column and stay in same row
                    col = col + 1
                #GO TO NEXT CELL #recursive solve with actual state of sudoku, changed row and col and number 1 - because checking values in new cell starts from 1
                return solve(sudoku, on_start, row, col, 1, go_back=False,rec = rec + 1)
                #####
            #if not possible to put number in cell
            else:
                #if number is 9 - error
                if number == 9:
                    #INSTEAD OF ERROR NOW I NEED TO PUT HERE MECHANISM THAT WILL GO BACK AND 
                    #TRY TO PUT ANOTHER POSSIBLE NUMBER IN PREVIOUS CELL THAT WASN'T FILLED ON START
                    #WILL DO IT USING ON_START VARIABLE
                    sudoku = restart_next_cells(sudoku, on_start, row, col)
                    if col == 0:
                        if row == 0:
                            print("Recursion: {}".format(rec))
                            print(datetime.datetime.now())
                            return sudoku
                        else:
                            col = 8
                            row = row - 1
                    else:
                        col = col - 1
                    return solve(sudoku, on_start, row, col, 0, go_back=True,rec = rec + 1)
                #if number is not 9 (less than 9) recursive solve with number = number + 1
                else:
                    return solve(sudoku, on_start, row, col, number + 1, go_back=False,rec = rec + 1)
        #if cell != 0 then don't check possibilities
        else:
            #####
            #if last column
            if col == 8:
                #if last row
                if row == 8:
                    #we are in last cell and it is not equal to 0 -> return sudoku
                    print("Recursion: {}".format(rec))
                    print(datetime.datetime.now())
                    return sudoku
                #if not last row
                else:
                    #go to firs (0) column and next row
                    col = 0
                    row = row + 1
            #if not last column
            else:
                #go to next column and stay in same row
                col = col + 1
            #GO TO NEXT CELL #recursive solve with actual state of sudoku, changed row and col and number 1 - because checking values in new cell starts from 1
            return solve(sudoku, on_start, row, col, 1, go_back=False,rec = rec + 1)
            #####
    
    

In [13]:
#sudoku = clear_sudoku()
#sudoku = example_easy_sudoku()
#sudoku = example_medium_sudoku()
#sudoku = example_hard_sudoku()
sudoku = example_evil_sudoku()

In [14]:
sudoku

[array([[6, 0, 0, 4, 0, 0, 0, 0, 0],
        [0, 0, 2, 0, 5, 3, 0, 1, 0],
        [8, 0, 0, 0, 2, 0, 0, 0, 4],
        [1, 0, 9, 5, 0, 0, 7, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 6, 0, 0, 4, 9, 0, 5],
        [2, 0, 0, 0, 6, 0, 0, 0, 7],
        [0, 3, 0, 9, 4, 0, 2, 0, 0],
        [0, 0, 0, 0, 0, 8, 0, 0, 9]]), array([[0, 3, 7, 0, 5, 0, 0, 0, 0],
        [0, 0, 0, 6, 8, 0, 0, 0, 2],
        [0, 0, 4, 0, 2, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 5, 0, 0, 6],
        [9, 2, 0, 0, 0, 0, 0, 4, 1],
        [1, 0, 0, 2, 0, 0, 0, 0, 0],
        [0, 6, 0, 0, 4, 0, 2, 0, 0],
        [4, 0, 0, 0, 3, 2, 0, 0, 0],
        [0, 0, 0, 0, 6, 0, 3, 7, 0]]), array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 5, 3, 0, 0, 4, 8, 7, 0],
        [0, 0, 0, 0, 0, 1, 4, 0, 9],
        [0, 1, 0, 0, 6, 0, 0, 0, 0],
        [7, 9, 0, 0, 0, 0, 0, 3, 4],
        [0, 0, 0, 0, 1, 0, 0, 2, 0],
        [3, 0, 5, 6, 0, 0, 0, 0, 0],
        [0, 8, 1, 3, 0, 0, 2, 9, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [15]:
#on_start is array which have 1 in cells filled no start and 0 it cells not filled
on_start = np.copy(sudoku)
np.place(on_start, on_start>0, [True])
print(on_start)
#print(sudoku)

[[[1 0 0 1 0 0 0 0 0]
  [0 0 1 0 1 1 0 1 0]
  [1 0 0 0 1 0 0 0 1]
  [1 0 1 1 0 0 1 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 1 0 0 1 1 0 1]
  [1 0 0 0 1 0 0 0 1]
  [0 1 0 1 1 0 1 0 0]
  [0 0 0 0 0 1 0 0 1]]

 [[0 1 1 0 1 0 0 0 0]
  [0 0 0 1 1 0 0 0 1]
  [0 0 1 0 1 0 0 1 0]
  [0 0 0 0 0 1 0 0 1]
  [1 1 0 0 0 0 0 1 1]
  [1 0 0 1 0 0 0 0 0]
  [0 1 0 0 1 0 1 0 0]
  [1 0 0 0 1 1 0 0 0]
  [0 0 0 0 1 0 1 1 0]]

 [[0 0 0 0 0 0 0 0 0]
  [0 1 1 0 0 1 1 1 0]
  [0 0 0 0 0 1 1 0 1]
  [0 1 0 0 1 0 0 0 0]
  [1 1 0 0 0 0 0 1 1]
  [0 0 0 0 1 0 0 1 0]
  [1 0 1 1 0 0 0 0 0]
  [0 1 1 1 0 0 1 1 0]
  [0 0 0 0 0 0 0 0 0]]]


In [16]:
# for easier sudoku
#%%time
#sudoku = solve(sudoku, on_start, 0, 0, 1, go_back=False, rec=0)

In [17]:
sudoku

[array([[6, 0, 0, 4, 0, 0, 0, 0, 0],
        [0, 0, 2, 0, 5, 3, 0, 1, 0],
        [8, 0, 0, 0, 2, 0, 0, 0, 4],
        [1, 0, 9, 5, 0, 0, 7, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 6, 0, 0, 4, 9, 0, 5],
        [2, 0, 0, 0, 6, 0, 0, 0, 7],
        [0, 3, 0, 9, 4, 0, 2, 0, 0],
        [0, 0, 0, 0, 0, 8, 0, 0, 9]]), array([[0, 3, 7, 0, 5, 0, 0, 0, 0],
        [0, 0, 0, 6, 8, 0, 0, 0, 2],
        [0, 0, 4, 0, 2, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 5, 0, 0, 6],
        [9, 2, 0, 0, 0, 0, 0, 4, 1],
        [1, 0, 0, 2, 0, 0, 0, 0, 0],
        [0, 6, 0, 0, 4, 0, 2, 0, 0],
        [4, 0, 0, 0, 3, 2, 0, 0, 0],
        [0, 0, 0, 0, 6, 0, 3, 7, 0]]), array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 5, 3, 0, 0, 4, 8, 7, 0],
        [0, 0, 0, 0, 0, 1, 4, 0, 9],
        [0, 1, 0, 0, 6, 0, 0, 0, 0],
        [7, 9, 0, 0, 0, 0, 0, 3, 4],
        [0, 0, 0, 0, 1, 0, 0, 2, 0],
        [3, 0, 5, 6, 0, 0, 0, 0, 0],
        [0, 8, 1, 3, 0, 0, 2, 9, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [18]:
threading.stack_size(67108864) # 64MB stack
sys.setrecursionlimit(2 ** 20) # something real big
                               # you actually hit the 64MB limit first
                               # going by other answers, could just use 2**32-1

In [19]:
thread = threading.Thread(target=solve, args = (sudoku[0], on_start[0], 0, 0, 1, False, 0, ))
thread.start()

Recursion: 0
2020-02-27 13:01:29.911956
Recursion: 1000
Recursion: 2000
Recursion: 3000
Recursion: 4000
Recursion: 5000
Recursion: 6000
Recursion: 7000
Recursion: 8000
Recursion: 9000
Recursion: 10000
Recursion: 11000
Recursion: 12000
Recursion: 13000
Recursion: 14000
Recursion: 15000
Recursion: 16000
Recursion: 17000
Recursion: 18000
Recursion: 19000
Recursion: 20000
Recursion: 21000
Recursion: 22000
Recursion: 23000
Recursion: 24000
Recursion: 25000
Recursion: 26000
Recursion: 27000
Recursion: 28000
Recursion: 29000
Recursion: 30000
Recursion: 31000
Recursion: 32000
Recursion: 33000
Recursion: 34000
Recursion: 35000
Recursion: 36000
Recursion: 37000
Recursion: 38000
Recursion: 39000
Recursion: 40000
Recursion: 41000
Recursion: 41017
2020-02-27 13:01:30.259616


In [20]:
thread = threading.Thread(target=solve, args = (sudoku[1], on_start[1], 0, 0, 1, False, 0, ))
thread.start()

Recursion: 0
2020-02-27 13:01:32.664214
Recursion: 1000
Recursion: 2000
Recursion: 3000
Recursion: 4000
Recursion: 5000
Recursion: 6000
Recursion: 7000
Recursion: 8000
Recursion: 9000
Recursion: 10000
Recursion: 10416
2020-02-27 13:01:32.764471


In [21]:
thread = threading.Thread(target=solve, args = (sudoku[2], on_start[2], 0, 0, 1, False, 0, ))
thread.start()

Recursion: 0
2020-02-27 13:01:34.542384
Recursion: 1000
Recursion: 2000
Recursion: 3000
Recursion: 4000
Recursion: 5000
Recursion: 6000
Recursion: 7000
Recursion: 8000
Recursion: 9000
Recursion: 10000
Recursion: 11000
Recursion: 12000
Recursion: 13000
Recursion: 14000
Recursion: 15000
Recursion: 16000
Recursion: 17000
Recursion: 18000
Recursion: 19000
Recursion: 20000
Recursion: 21000
Recursion: 22000
Recursion: 23000
Recursion: 24000
Recursion: 25000
Recursion: 26000
Recursion: 27000
Recursion: 28000
Recursion: 29000
Recursion: 30000
Recursion: 31000
Recursion: 31899
2020-02-27 13:01:34.874390


In [31]:
sudoku

[array([[2, 8, 6, 3, 7, 5, 9, 1, 4],
        [4, 5, 1, 8, 9, 6, 7, 3, 2],
        [9, 3, 7, 4, 1, 2, 5, 6, 8],
        [5, 1, 4, 7, 2, 8, 6, 9, 3],
        [6, 7, 3, 9, 5, 4, 8, 2, 1],
        [8, 2, 9, 6, 3, 1, 4, 7, 5],
        [1, 4, 2, 5, 6, 7, 3, 8, 9],
        [3, 6, 5, 1, 8, 9, 2, 4, 7],
        [7, 9, 8, 2, 4, 3, 1, 5, 6]]), array([[9, 7, 6, 4, 1, 8, 3, 2, 5],
        [1, 8, 3, 2, 7, 5, 6, 9, 4],
        [5, 2, 4, 6, 3, 9, 7, 1, 8],
        [7, 3, 5, 8, 6, 2, 1, 4, 9],
        [4, 6, 2, 7, 9, 1, 5, 8, 3],
        [8, 1, 9, 5, 4, 3, 2, 6, 7],
        [3, 5, 1, 9, 2, 4, 8, 7, 6],
        [2, 9, 7, 3, 8, 6, 4, 5, 1],
        [6, 4, 8, 1, 5, 7, 9, 3, 2]]), array([[8, 4, 5, 6, 7, 1, 2, 9, 3],
        [2, 3, 6, 4, 5, 9, 7, 1, 8],
        [1, 7, 9, 8, 3, 2, 5, 4, 6],
        [6, 8, 4, 5, 1, 3, 9, 2, 7],
        [5, 2, 3, 7, 9, 6, 1, 8, 4],
        [7, 9, 1, 2, 4, 8, 3, 6, 5],
        [3, 5, 8, 9, 2, 4, 6, 7, 1],
        [4, 1, 2, 3, 6, 7, 8, 5, 9],
        [9, 6, 7, 1, 8, 5, 4, 3, 2]]