This code is copied from Computerphile's video about solving sudoku

In [25]:
import numpy as np
import datetime

In [26]:
#sudoku = np.zeros(81,dtype="int").reshape(9,9)
def clear_sudoku():
    sudoku = [[0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0]]

    sudoku = np.array(sudoku)
    return sudoku

Examples are from websudoku.com

In [27]:
def example_easy_sudoku():
    sudoku = []
    sudoku.append(np.array([[0, 4, 0, 0, 0, 3, 0, 6, 0],
                 [6, 0, 8, 9, 0, 1, 5, 7, 0],
                 [0, 2, 0, 7, 6, 0, 0, 0, 3],
                 [2, 0, 0, 4, 5, 7, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 2, 1, 9, 0, 0, 6],
                 [3, 0, 0, 0, 9, 4, 0, 5, 0],
                 [0, 9, 5, 6, 0, 2, 8, 0, 1],
                 [0, 7, 0, 1, 0, 0, 0, 9, 0]]))

    sudoku.append(np.array([[0, 5, 0, 1, 4, 0, 0, 0, 2],
                 [7, 0, 1, 0, 0, 9, 0, 0, 4],
                 [4, 3, 0, 6, 0, 0, 0, 0, 0],
                 [5, 0, 3, 0, 9, 1, 2, 0, 0],
                 [0, 1, 0, 3, 0, 6, 0, 5, 0],
                 [0, 0, 7, 5, 2, 0, 6, 0, 1],
                 [0, 0, 0, 0, 0, 8, 0, 9, 5],
                 [9, 0, 0, 4, 0, 0, 8, 0, 3],
                 [1, 0, 0, 0, 7, 3, 0, 2, 0]]))
    
    sudoku.append(np.array([[0, 8, 0, 0, 3, 5, 9, 0, 0],
                 [0, 0, 6, 1, 0, 0, 0, 0, 0],
                 [2, 0, 0, 0, 9, 0, 8, 7, 0],
                 [0, 0, 0, 3, 5, 0, 1, 2, 4],
                 [1, 4, 3, 0, 0, 0, 7, 5, 8],
                 [5, 7, 2, 0, 4, 1, 0, 0, 0],
                 [0, 2, 9, 0, 7, 0, 0, 0, 6],
                 [0, 0, 0, 0, 0, 4, 2, 0, 0],
                 [0, 0, 4, 9, 2, 0, 0, 3, 0]]))

    return sudoku

In [28]:
def example_medium_sudoku():
    sudoku = []
    sudoku.append(np.array([[0, 8, 6, 3, 0, 0, 0, 0, 4],
                 [0, 0, 1, 0, 9, 0, 0, 0, 0],
                 [0, 0, 0, 4, 1, 2, 0, 6, 0],
                 [5, 1, 0, 0, 0, 0, 0, 0, 3],
                 [6, 0, 3, 0, 5, 0, 8, 0, 1],
                 [8, 0, 0, 0, 0, 0, 0, 7, 5],
                 [0, 4, 0, 5, 6, 7, 0, 0, 0],
                 [0, 0, 0, 0, 8, 0, 2, 0, 0],
                 [7, 0, 0, 0, 0, 3, 1, 5, 0]]))

    sudoku.append(np.array([[9, 7, 0, 4, 0, 0, 0, 0, 5],
                 [0, 8, 3, 2, 0, 5, 0, 0, 0],
                 [0, 0, 4, 6, 0, 0, 7, 0, 0],
                 [7, 3, 0, 8, 0, 0, 0, 4, 0],
                 [0, 0, 0, 7, 0, 1, 0, 0, 0],
                 [0, 1, 0, 0, 0, 3, 0, 6, 7],
                 [0, 0, 1, 0, 0, 4, 8, 0, 0],
                 [0, 0, 0, 3, 0, 6, 4, 5, 0],
                 [6, 0, 0, 0, 0, 7, 0, 3, 2]]))
    
    sudoku.append(np.array([[0, 4, 0, 0, 0, 0, 0, 9, 3],
                 [0, 0, 0, 0, 5, 0, 7, 0, 0],
                 [0, 0, 0, 0, 3, 2, 5, 0, 6],
                 [0, 0, 0, 0, 0, 0, 9, 0, 7],
                 [5, 2, 0, 7, 9, 6, 0, 8, 4],
                 [7, 0, 1, 0, 0, 0, 0, 0, 0],
                 [3, 0, 8, 9, 2, 0, 0, 0, 0],
                 [0, 0, 2, 0, 6, 0, 0, 0, 0],
                 [9, 6, 0, 0, 0, 0, 0, 3, 0]]))

    return sudoku

In [29]:
def example_hard_sudoku():
    sudoku = []
    sudoku.append(np.array([[0, 0, 0, 0, 0, 5, 0, 0, 0],
                 [0, 0, 7, 6, 0, 0, 4, 0, 0],
                 [3, 0, 0, 0, 7, 0, 0, 1, 0],
                 [0, 0, 9, 0, 0, 8, 0, 5, 0],
                 [5, 0, 3, 9, 0, 2, 6, 0, 1],
                 [0, 4, 0, 1, 0, 0, 2, 0, 0],
                 [0, 3, 0, 0, 8, 0, 0, 0, 9],
                 [0, 0, 6, 0, 0, 4, 5, 0, 0],
                 [0, 0, 0, 7, 0, 0, 0, 0, 0]]))

    sudoku.append(np.array([[0, 3, 7, 0, 5, 0, 0, 0, 0],
                 [0, 0, 0, 6, 8, 0, 0, 0, 2],
                 [0, 0, 4, 0, 2, 0, 0, 1, 0],
                 [0, 0, 0, 0, 0, 5, 0, 0, 6],
                 [9, 2, 0, 0, 0, 0, 0, 4, 1],
                 [1, 0, 0, 2, 0, 0, 0, 0, 0],
                 [0, 6, 0, 0, 4, 0, 2, 0, 0],
                 [4, 0, 0, 0, 3, 2, 0, 0, 0],
                 [0, 0, 0, 0, 6, 0, 3, 7, 0]]))
    
    sudoku.append(np.array([[6, 0, 0, 5, 0, 0, 0, 0, 1],
                 [0, 9, 0, 7, 0, 8, 5, 0, 0],
                 [0, 1, 0, 3, 0, 0, 0, 8, 0],
                 [1, 0, 8, 0, 3, 0, 6, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 6, 0, 8, 0, 3, 0, 9],
                 [0, 4, 0, 0, 0, 3, 0, 9, 0],
                 [0, 0, 9, 2, 0, 5, 0, 1, 0],
                 [8, 0, 0, 0, 0, 9, 0, 0, 7]]))

    return sudoku

In [30]:
def example_evil_sudoku():
    sudoku = []
    sudoku.append(np.array([[6, 0, 0, 4, 0, 0, 0, 0, 0],
                 [0, 0, 2, 0, 5, 3, 0, 1, 0],
                 [8, 0, 0, 0, 2, 0, 0, 0, 4],
                 [1, 0, 9, 5, 0, 0, 7, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 6, 0, 0, 4, 9, 0, 5],
                 [2, 0, 0, 0, 6, 0, 0, 0, 7],
                 [0, 3, 0, 9, 4, 0, 2, 0, 0],
                 [0, 0, 0, 0, 0, 8, 0, 0, 9]]))

    sudoku.append(np.array([[0, 3, 7, 0, 5, 0, 0, 0, 0],
                 [0, 0, 0, 6, 8, 0, 0, 0, 2],
                 [0, 0, 4, 0, 2, 0, 0, 1, 0],
                 [0, 0, 0, 0, 0, 5, 0, 0, 6],
                 [9, 2, 0, 0, 0, 0, 0, 4, 1],
                 [1, 0, 0, 2, 0, 0, 0, 0, 0],
                 [0, 6, 0, 0, 4, 0, 2, 0, 0],
                 [4, 0, 0, 0, 3, 2, 0, 0, 0],
                 [0, 0, 0, 0, 6, 0, 3, 7, 0]]))
    
    sudoku.append(np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 5, 3, 0, 0, 4, 8, 7, 0],
                 [0, 0, 0, 0, 0, 1, 4, 0, 9],
                 [0, 1, 0, 0, 6, 0, 0, 0, 0],
                 [7, 9, 0, 0, 0, 0, 0, 3, 4],
                 [0, 0, 0, 0, 1, 0, 0, 2, 0],
                 [3, 0, 5, 6, 0, 0, 0, 0, 0],
                 [0, 8, 1, 3, 0, 0, 2, 9, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0]]))

    return sudoku

In [31]:
#sudoku[1,3] - value from row 1 and col 3
#sudoku[:,3] - whole column 3
#sudoku[1,:] - whole row 1

In [32]:
def possible(y,x,n, sudoku):
    for i in range(0,9):
        if sudoku[y][i] == n:
            return False
    for i in range(0,9):
        if sudoku[i][x] == n:
            return False
    x0 = (x//3)*3
    y0 = (y//3)*3
    for i in range(0,3):
        for j in range(0,3):
            if sudoku[y0+i][x0+j] == n:
                return False
    return True

In [33]:
#sudoku = example_easy_sudoku()
## checking if function works
#possible(0, 0, 5, sudoku[0])

In [34]:
def solve(sudoku):
    for y in range(9):
        for x in range(9):
            if sudoku[y][x] == 0:
                for n in range(1,10):
                    if possible(y,x,n,sudoku):
                        sudoku[y][x] = n
                        solve(sudoku)
                        sudoku[y][x] = 0
                return
    print(sudoku)
    input("More?")

In [35]:
#sudoku = clear_sudoku()
#sudoku = example_easy_sudoku()
#sudoku = example_medium_sudoku()
#sudoku = example_hard_sudoku()
sudoku = example_evil_sudoku()

In [36]:
sudoku

[array([[6, 0, 0, 4, 0, 0, 0, 0, 0],
        [0, 0, 2, 0, 5, 3, 0, 1, 0],
        [8, 0, 0, 0, 2, 0, 0, 0, 4],
        [1, 0, 9, 5, 0, 0, 7, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 6, 0, 0, 4, 9, 0, 5],
        [2, 0, 0, 0, 6, 0, 0, 0, 7],
        [0, 3, 0, 9, 4, 0, 2, 0, 0],
        [0, 0, 0, 0, 0, 8, 0, 0, 9]]), array([[0, 3, 7, 0, 5, 0, 0, 0, 0],
        [0, 0, 0, 6, 8, 0, 0, 0, 2],
        [0, 0, 4, 0, 2, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 5, 0, 0, 6],
        [9, 2, 0, 0, 0, 0, 0, 4, 1],
        [1, 0, 0, 2, 0, 0, 0, 0, 0],
        [0, 6, 0, 0, 4, 0, 2, 0, 0],
        [4, 0, 0, 0, 3, 2, 0, 0, 0],
        [0, 0, 0, 0, 6, 0, 3, 7, 0]]), array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 5, 3, 0, 0, 4, 8, 7, 0],
        [0, 0, 0, 0, 0, 1, 4, 0, 9],
        [0, 1, 0, 0, 6, 0, 0, 0, 0],
        [7, 9, 0, 0, 0, 0, 0, 3, 4],
        [0, 0, 0, 0, 1, 0, 0, 2, 0],
        [3, 0, 5, 6, 0, 0, 0, 0, 0],
        [0, 8, 1, 3, 0, 0, 2, 9, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [37]:
solve(sudoku[2])

[[1 4 9 7 8 6 3 5 2]
 [6 5 3 2 9 4 8 7 1]
 [2 7 8 5 3 1 4 6 9]
 [5 1 2 4 6 3 9 8 7]
 [7 9 6 8 5 2 1 3 4]
 [8 3 4 9 1 7 6 2 5]
 [3 2 5 6 4 9 7 1 8]
 [4 8 1 3 7 5 2 9 6]
 [9 6 7 1 2 8 5 4 3]]


More? 
